
version: '3.8'

services:
  db:
    image: mariadb:10.5
    container_name: tdmu-dispatch-mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT:-3306}:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - tdmu-dispatch-network

  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev.backend
    container_name: tdmu-backend-dev
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - tdmu-dispatch-network

  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev.frontend
    container_name: tdmu-frontend-dev
    volumes:
      - .:/app
    ports:
      - "4200:4200"
    env_file:
      - .env
    depends_on:
      - backend
    networks:
      - tdmu-dispatch-network

volumes:
  db_data:

networks:
  tdmu-dispatch-network:

